services:
  mysql:
    image: mysql:8.0
    container_name: kaddem-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring:
    image: hamzambarki/kaddem:latest
    container_name: hamzambarki-kaddem
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SERVER_PORT: 8809
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kaddem?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8809:8809"
    depends_on:
      - mysql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - spring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  mysql-data: