sonar.projectKey=MelekJdidi-G5-Kaddem
sonar.projectName=MelekJdidi-G5-Kaddem
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.login=sqa_4da7f657c276d42718dfa0431a43d4f2c9e777f7
