sonar.projectKey=4TWIN1-G5-Kaddem
sonar.projectName=4TWIN1-G5-Kaddem
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.login=sqa_b7360ec0a37a66135205ad6a976b71e4c38ce815

